# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9XlAKr1UXcx0uw4BHJEoEwreWO08_5O
"""

# Calculadora

while True:
  num1= float(input('digite o primeiro numero:'))
  operações= input('digite a operação: ')
  num2= float(input('digite o segundo numero:'))

  if operações == '+':
    resultado= num1 + num2
  elif operações == '-':
    resultado= num1 - num2
  elif operações == '*':
    resultado= num1 * num2
  elif operações == '/':
    if num2 == 0:
      resultado = "não é possivel dividir por zero"
    else:
      resultado= num1 / num2
  else:
    resultado = "operação invalida"
  print(f'Resultado: {resultado}')
  # Verifica se o resultado é um número antes de tentar o módulo
  if resultado % 2 == 0:
      print('o resultado é par')
  else:
      print('o resultado é impar')
  # Solicita ao usuário se deseja continuar
  resposta_continuar = input('Deseja continuar? (sim/nao) ')
  if resposta_continuar == 'nao':
    break

